language: scala
scala:
  - 2.12.3
sudo: required
addons:
  chrome: stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - nvm install node
  - nvm use node
  - cd frontend
  - npm install
  - npm install -g @angular/cli
script:
  - cd ../backend
  - sbt test
  - sbt dist
  - cd ../frontend
  - ng build
  - ng test --single-run
