matrix:
  include:
    - language: scala
      scala:
        - 2.12.3
      before_script:
        - cd backend
      script:
        - sbt test
        - sbt dist
  include:
    - language: node_js
      node_js:
        - '8'
      sudo: required
      addons:
        chrome: stable
      before_install:
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      before_script:
        - cd frontend
        - npm install
      script:
        - ng build
        - ng test --single-run