language: scala
scala:
- 2.12.3
sudo: required
addons:
  chrome: stable
services:
- docker
before_install:
- docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD";
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- nvm install node
- nvm use node
- cd frontend
- npm install
- npm install -g @angular/cli
script:
- cd ../backend
- sbt test
- sbt dist
- cd ../frontend
- ng build
- ng test --single-run
after_success:
- docker build -t $DOCKER_HUB_USERNAME/issue-tracker ./backend
- docker build -t $DOCKER_HUB_USERNAME/issue-tracker ./frontend
- docker push $DOCKER_HUB_USERNAME/issue-tracker-backend:1.0.0
- docker push $DOCKER_HUB_USERNAME/issue-tracker-frontend:1.0.0
env:
  global:
  - secure: Ky3ZLyteydoyVC+8zjMaT+cQthUjGm9cpVEMjLptgea/W6Aa9NsYcQ9bK0cctmflsUoNQRn2UmswxnObKFyWR4EpHCGXARDT3R/KmimZAt0/Ex/7CrRqhNVVHgZq/Ld4qooEKr39kBvsf9e/sjM/yR/VW0NNJ4YBncXU4k5yD4xtLy+Acj9RfQRTn5g6Yu/UaD9aWN7hSKTBSHatJF3G/V9UMOWgvrO/kze3D63qUfGYYuqlHCJhldWUjih8i9iCHJSZSYlHDifr9jFLsn/U6OJU/MAluDhIHq5KATKVsh9iWFxT3yVjKNyhEyYM8pf5ZIYyPBpWjkZaThBaAG5lxJKeAkGU9x5KpS59x4bOpk9xEjP7/yiUR/KRqdagJSOXLoOU625DR21VRNtNB6aD2I9LphfTm5vB+0nLvoSHTYMY6B/lUWEZYOmtV86L+EaAL6jnBEJeVXS8MP7tLNH+ZZr4AM4nu57P0oTmyzdRyHqcVjd09SKFqmouL34GK8wxeUthQKKLHWtNlp4VmuEYetwlotHfo6XNZDNTHT4UZJaTJNQ7oFwwVoNcK2Bs8/dGNKU4pWfu+maRyQyORJ1pWwfjVuG2nIgTxTMRzGxolIWm7tEciIVHQ/MfD1fRVdlC4B9F0ICwDmWtGTqi0M5ScFmqXEegFYDvjeeCHYlZpDo=
  - secure: dRy6aiDJjUGP5+1BFJ7yIYS0DsC+zXdj+XuonIuTdC6s99JPl54kEsXTXNfMOiIYvCBVFS/sI3JFGd9zHD9mRc8YEDqc6LjHYs0iAve7vGNLRn8xW4EiS09z6iDBe79mg8aSrdqgIAThcEJ5FVvxqTwmVAtYTJAoEvJ5WTySMAnbaEy90XHZ91Xu2ohA8crE8HZKhvoB51C3MpnC6FR69Ca581t6M493xZtcPdEq7t2veQcQdUaoxflY3nlEnW2sWNqWH+TtT9szY6RatYy0OXDTuw3jTZxM/rr5vgJAK/k8KjhOKgfM0n+HPKRMyqXGFf+79rzdPQ0MKBY49F0ex/cNy4KE1gdsHteVy1pmOYNebXZJpy9eN7xX61b4mkbRs7e1uA+zkY3HpwKlFRLTzdgPgk8bC+rOlyQChaxKVDgxGMHzE46BEr1iv7xCxGEoha/w8vAOEkgwwnq9L3sRhQPl5GOtoQCrWqgNRZOeJlPVkyQ9MyKYeCkW/iHpw9FtSsaNdvuwJ0a/4B4BSFR5/wgT9U1vR7sij3WYgFfTzpdqK8mDkSEjAppxIcI7yc9c4PejfbfDXD+KTyqbywRQkZkpTAh4E0HfApWPuxPor9LAP5NyjRbkVhthSdFiDNxahrZDxReeYrp4BuiI6+rP5I25IAfjBpiqKOmWyGSEKLI=
  - secure: ifvOEjiw9+IE1s2ulmmqxMOiIxZlDjDPS2kzbRZfO59oADFjp1vRTrV6C1uNsyxAlqqCusRKc2WUfAbwmfdJS58oZ8BfC6l5NLiayii2gRyS/t9timmmYAp2xwdpJdoFMmZ8STc8KhWDGZL4YTGwRCipu9jSnNMMNbRhy3/QKHaM6+N3n7kH/ib7wipNcURI/P3sQQtTMSJf1T16GjV+qcLjBp7kR8qb6t5o2i0yli/Z/GRViMa+L+JvTLLVvRuy6rAdYBMcItqzvJ3qTGAgSmLKHq6wofni4KLdArYIiBfmMmQoPxqV6PE/TQo/sc496YrACWhtABZJN+kqvPoSIkilWCOmIywY2LBFX+4WUN53DTWD0HXHkdAaBAdhngxHwQ7FkDRAPbgD8Mty3//VH1wGLciAZ/Lg5Fuxzh75WDAENOqlDlSGkr0GmiL+Lj7ojXyd7QjvSUMnk4rXdu4Md3ABy2Um+RT3cXpK4lbpMc+U7yOOHrcBow4V+n4xQNTONxXaF35qkKUxqpQDe8Dkb/TvcUQITioKxjuUafkMZtAXhH4jcehe4R29yvVlQ94c4PdVqqy1if2sQ9YO/kS486kV21MhVA47uZz6FEyJYCWIv0/t2TUCFdKF5EQf3buGllSdQZIZ6ziZ+SrvLe08fPat312e27DkY4Gc1X2fxtk=
